### PR TITLE
Bring this package up to date to use with the new noir/nargo

### PR DESCRIPTION
**Pull request by LogvinovLeon**
Currently - it's impossible to use this package as a dependency because of a couple reasons:
* nargo disallows hyphens in package names:
https://github.com/noir-lang/noir/blob/4467ea9e285ec810f45052e469ac2c1f9903a7d3/compiler/noirc_frontend/src/graph/mod.rs#L109
```
[tooling/nargo_toml/src/lib.rs:130] name.parse() = Err(
    "Package names must be non-empty and cannot contain hyphens",
)
Invalid package name `noir-u2b` found in /Users/leonidlogvinov/nargo/github.com/colinnielsen/noir-u2bv0.3.0/Nargo.toml
```
* There is no package type specified
* All functions are private
* Library crates should have lib.nr instead of main.nr
* Compiler version is fixed to 0.8.0
* 
This PR fixes that and makes it possible to import this lib into modern projects

### CODE REVIEW

**Comment by LogvinovLeon** [comment]
@colinnielsen Please let me know if there is anything blocking this PR from merging

**Comment by colinnielsen** [comment]
> @colinnielsen Please let me know if there is anything blocking this PR from merging

looks great - thanks!

**Comment by colinnielsen** [comment]
> @colinnielsen Please let me know if there is anything blocking this PR from merging

actually - looks like CI is failing, do you mind bumping the version in CI?

**Comment by LogvinovLeon** [comment]
I can't run CI on this PR, but it passes now in my fork

**Comment by colinnielsen** [comment]
> I can't run CI on this PR, but it passes now in my fork

passes! merging now, thanks

**Pull request merged**
